# Site settings
title: Android Notes
description: >
  Learning Android development by teaching

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://androidnotes.github.io" # the base hostname & protocol for your site

author:
  fullname: Al John Quiapon
  github: androidnotes
  disqus: androidnotes

google_analytics: 'UA-71000981-2'

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
